name: Java CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: self-hosted
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and Publish with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        with:
          arguments: build -x test publish --stacktrace --no-daemon